### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by ofpiyush**
Error handling is broken for single error cases.

This PR fixes it.

### CODE REVIEW

**Comment by harlow** [comment]
hi @ofpiyush thanks for the PR. are the tests passing locally for you? it looks like they are failing on Travis CI.

**Comment by ofpiyush** [comment]
@harlow check the error logs. The tests ask for authentication.

**Comment by sdalezman** [comment]
any update on this one? happy to push up fix but was curious if this is still being maintained...caused some issues for us today in not realizing we were hitting 429 errors

**Comment by ofpiyush** [comment]
I am not sure if it is being maintained either. We're using our fork with the bugfix. 🤞

**Comment by harlow** [comment]
Hi all, sorry for the lack of response here. I'm gonna get this merged and then i'll create a sep PR to fix the auth issues on Travis.

**Pull request merged**
