### PR TITLE
refactoring to allow passing in of custom base urls to allow for mocking

### PR DESCRIPTION
**Pull request by heyweswu**
https://github.com/clearbit/clearbit-go/issues/5

### CODE REVIEW

**Review by harlow — COMMENTED** [review]
Thanks for the PR 🙏

Will have the team review this week and get it merged

**Comment by heyweswu** [comment]
> Thanks for the PR 🙏
> 
> Will have the team review this week and get it merged

@harlow any updates here?

**Comment by harlow** [comment]
@heyweswu sorry for the delays. this looks good. thanks for the PR.

**Comment by mcculleydj** [comment]
@harlow any chance this can get published so we can stop relying on a fork? Ty!

**Comment by harlow** [comment]
@mcculleydj the changes have been merged to master. When you say "published" would you like a Tag cut or something? just wanna make sure I'm understanding

**Comment by mcculleydj** [comment]
@harlow Yea that's what I'm asking for. Sorry that could've been stated more clearly. From https://blog.golang.org/publishing-go-modules:

Once you start tagging your repo with versions, it's important to keep tagging new releases as you develop your module. When users request a new version of your module (with go get -u or go get example.com/hello), the go command will choose the greatest semantic release version available, even if that version is several years old and many changes behind the primary branch. Continuing to tag new releases will make your ongoing improvements available to your users.

---

Happy to be wrong about the need for this. I'm not an expert in Go's package management and I know that the approach has changed in the not too distant past (i.e. no longer using go get). I started to recommend abandoning our fork since this PR was merged, until I saw that we may not have access to the latest changes using go mod (https://pkg.go.dev/github.com/clearbit/clearbit-go).

Thanks for the quick reply! Hopefully, I'm not wasting your time by asking for something unnecessary.

**Comment by harlow** [comment]
@mcculleydj thanks for the post. I've cut a `v1.0.1` tag: https://github.com/clearbit/clearbit-go/tags

**Pull request merged**
